import http from "node:http";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { resolve, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(fileURLToPath(new URL(".", import.meta.url)));
const fixture = join(root, "fixture.html");
const port = Number(process.env.PORT ?? 8899);
const runs = new Map();
const subscribers = new Set();
const maxEvents = 5000;

function emit(run, type, data = {}) { const event = { ts: new Date().toISOString(), runId: run.id, type, ...data }; run.events.push(event); if (run.events.length > maxEvents) run.events.shift(); for (const res of subscribers) res.write(`data: ${JSON.stringify(event)}\\n\\n`); }
function report(run) { return { runId: run.id, status: run.status, startedAt: run.startedAt, finishedAt: run.finishedAt, goal: run.goal, events: run.events, metrics: { gentleMs: run.events.filter(e => e.owner === "gentle").reduce((n,e) => n + (e.durationMs ?? 0), 0), jevMs: run.events.filter(e => e.owner === "jev").reduce((n,e) => n + (e.durationMs ?? 0), 0), browserMs: run.events.filter(e => e.owner === "browser").reduce((n,e) => n + (e.durationMs ?? 0), 0), inputTokens: run.events.reduce((n,e) => n + (e.inputTokens ?? 0), 0), outputTokens: run.events.reduce((n,e) => n + (e.outputTokens ?? 0), 0), jevCalls: run.events.filter(e => e.owner === "jev").length, toolCalls: run.events.filter(e => e.type === "tool_execution").length } }; }
async function runTask(goal) { const run = { id: randomUUID(), goal, status: "running", startedAt: new Date().toISOString(), events: [] }; runs.set(run.id, run); emit(run, "run_started", { owner: "gentle" });
  const gentleStart = performance.now(); emit(run, "state_built", { owner: "gentle", state: { goal, url: "fixture://search" }, inputTokens: 80 }); await new Promise(r => setTimeout(r, 8)); emit(run, "gentle_decision", { owner: "gentle", decision: "bounded_read_only_browser_loop", durationMs: performance.now() - gentleStart, confidence: 1 });
  const jevStart = performance.now(); let jevDecision = "click_search"; let confidence = 0.92; let usage = { inputTokens: 120, outputTokens: 24 }; let jevModel = "local-fallback"; if (process.env.TYPESAFE_API_KEY) { try { const { TypeSafeClient, choice, noul } = await import("@typesafe-ai/sdk"); const client = new TypeSafeClient(); const response = await client.systemOne({ state: { goal, url: "fixture://search", controls: ["search_input", "search_button"] }, questions: { action: choice("Choose the next browser action", { click_search: "click the search button", done: "finish if goal is met" }), goal_met: noul("Is the goal complete?") } }); jevDecision = response.answers.action?.choice ?? jevDecision; confidence = response.answers.action?.confidence ?? 0; usage = { inputTokens: response.usage?.inputTokens ?? response.usage?.input_tokens ?? 0, outputTokens: response.usage?.outputTokens ?? response.usage?.output_tokens ?? 0 }; jevModel = response.model ?? "jev"; } catch (error) { emit(run, "jev_error", { owner: "jev", durationMs: performance.now() - jevStart, error: error.name, fallback: true }); } } const lowConfidence = confidence < 0.75; if (lowConfidence) { emit(run, "jev_low_confidence", { owner: "gentle", confidence, threshold: 0.75, fallback: "click_search" }); jevDecision = "click_search"; } emit(run, "jev_decision", { owner: "jev", decision: jevDecision, confidence, model: jevModel, fallback: lowConfidence, durationMs: performance.now() - jevStart, ...usage });
  const browserStart = performance.now(); emit(run, "tool_execution", { owner: "browser", tool: "read_fixture_page", action: "observe", durationMs: 5 }); await new Promise(r => setTimeout(r, 5)); emit(run, "browser_result", { owner: "browser", url: "fixture://search", summary: "Synthetic search page observed", durationMs: performance.now() - browserStart }); run.status = "done"; run.finishedAt = new Date().toISOString(); emit(run, "run_finished", { owner: "gentle", outcome: "done" }); return report(run); }
function json(res, status, body, type = "application/json") { res.writeHead(status, { "content-type": `${type}; charset=utf-8`, "cache-control": "no-store" }); res.end(type === "application/json" ? JSON.stringify(body) : body); }
async function handler(req, res) { if (req.method === "GET" && req.url === "/favicon.ico") { res.writeHead(204); return res.end(); } if (req.method === "GET" && req.url === "/") return json(res, 200, await readFile(join(root, "web/index.html"), "utf8"), "text/html"); if (req.method === "GET" && req.url === "/events") { res.writeHead(200, { "content-type": "text/event-stream", "cache-control": "no-cache", connection: "keep-alive" }); subscribers.add(res); req.on("close", () => subscribers.delete(res)); return; } if (req.method === "GET" && req.url.startsWith("/api/report/")) { const run = runs.get(req.url.split("/").pop()); return run ? json(res, 200, report(run)) : json(res, 404, { error: "run not found" }); } if (req.method === "POST" && req.url === "/api/run") { let body = ""; for await (const chunk of req) body += chunk; const result = await runTask(JSON.parse(body).goal ?? "Find the result"); return json(res, 200, result); } return json(res, 404, { error: "not found" }); }
http.createServer(handler).listen(port, "127.0.0.1", () => console.log(`gentle-browser-jev: http://127.0.0.1:${port}`));
